name: Build and deploy webpage

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
        run: curl -sSf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh -s -- -y

      - name: Build WASM (web target)
        run: wasm-pack build --release --target web --out-dir pkg

      - name: Install binaryen (latest)
        run: |
          BIN_VER=124
          curl -L -o /tmp/bin.tgz https://github.com/WebAssembly/binaryen/releases/download/version_$BIN_VER/binaryen-version_$BIN_VER-x86_64-linux.tar.gz
          tar -xzf /tmp/bin.tgz -C /tmp
          echo "/tmp/binaryen-version_$BIN_VER/bin" >> $GITHUB_PATH

      - name: Optimize WASM (safe for reference types)
        run: |
          FILE=$(ls pkg/*_bg.wasm)
          /tmp/binaryen-version_124/bin/wasm-opt -Oz --enable-reference-types -o "$FILE" "$FILE"

      - name: Prepare site for deployment
        run: |
          mkdir -p dist
          cp -r web/* dist/
          cp -r pkg dist/pkg
          touch dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
